[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput --settings=config.settings_prod']

[start]
cmd = 'gunicorn config.wsgi --bind 0.0.0.0:$PORT'