[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = ['python -m pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput --settings=config.settings_prod']

[start]
cmd = 'python -m gunicorn config.wsgi --bind 0.0.0.0:$PORT'