providers = ["python"]

[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmd = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[phases.build]
cmd = "chmod +x start.sh"

[start]
cmd = "./start.sh"