# Generated by Django 5.2.4 on 2025-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='En Cave', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
