# Generated by Django 5.2.4 on 2025-07-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveavin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='productor',
            field=models.CharField(default='inconnu', max_length=100),
            preserve_default=False,
        ),
    ]
