# Generated by Django 5.2.4 on 2025-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveavin', '0002_bottle_productor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='color',
            field=models.CharField(choices=[('Rouge', 'Rouge'), ('Blanc', 'Blanc'), ('Rosé', 'Rosé'), ('Pétillant', 'Pétillant'), ('Autre', 'Autre')], default='Rouge', max_length=20),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='status',
            field=models.CharField(choices=[('En cave', 'En cave'), ('Bue', 'Bue')], default='En cave', max_length=20),
        ),
    ]
