# Generated by Django 5.2.4 on 2025-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveavin', '0003_alter_bottle_color_alter_bottle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
