# Generated by Django 5.2.4 on 2025-07-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveavin', '0004_bottle_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='country',
            field=models.CharField(default='France', max_length=50),
            preserve_default=False,
        ),
    ]
