# Generated by Django 5.2.4 on 2025-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveavin', '0005_bottle_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description / Notes'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valeur estimée (€)'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='grape',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cépage(s)'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bottles/', verbose_name='Photo de la bouteille'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Prix d'achat (€)"),
        ),
        migrations.AddField(
            model_name='bottle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
        migrations.AddField(
            model_name='bottle',
            name='purchase_place',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Lieu d'achat"),
        ),
        migrations.AddField(
            model_name='bottle',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Note (sur 5)'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tasting_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note de dégustation'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='color',
            field=models.CharField(choices=[('Rouge', 'Rouge'), ('Blanc', 'Blanc'), ('Rosé', 'Rosé'), ('Pétillant', 'Pétillant'), ('Autre', 'Autre')], default='Rouge', max_length=20, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du vin'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='productor',
            field=models.CharField(max_length=100, verbose_name='Producteur'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région/Appellation'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='status',
            field=models.CharField(choices=[('En cave', 'En cave'), ('Bue', 'Bue')], default='En cave', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='year',
            field=models.IntegerField(verbose_name='Millésime'),
        ),
    ]
