# Generated by Django 5.2.4 on 2025-08-11 11:31

import caveavin.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveavin', '0007_bottle_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottle',
            options={'ordering': ['-date_added', 'name'], 'verbose_name': 'Bouteille', 'verbose_name_plural': 'Bouteilles'},
        ),
        migrations.AlterField(
            model_name='bottle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bottles/', validators=[caveavin.validators.validate_image_file], verbose_name='Photo de la bouteille'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Utilisateur propriétaire de cette bouteille', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[caveavin.validators.validate_price], verbose_name="Prix d'achat (€)"),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[caveavin.validators.validate_quantity], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='year',
            field=models.IntegerField(validators=[caveavin.validators.validate_wine_year], verbose_name='Millésime'),
        ),
    ]
