from caveavin.models import Bottle
from django.contrib.auth.models import User

data = [
    {
        "name": "Château Margaux",
        "year": 2015,
        "productor": "Château Margaux",
        "country": "France",
        "region": "Bordeaux",
        "color": "Rouge",
        "grape": "Cabernet Sauvignon, Merlot",
        "quantity": 2,
        "status": "En cave",
        "price": 450,
        "estimated_value": 650,
        "purchase_place": "Caviste Bordeaux",
        "purchase_date": "2018-12-10",
        "description": "Grand vin classique, potentiel de garde.",
        "tasting_note": "Nez complexe, tanins fins, longueur exceptionnelle.",
        "rating": 5,
    },
    {
        "name": "Domaine Leflaive Puligny-Montrachet",
        "year": 2018,
        "productor": "Domaine Leflaive",
        "country": "France",
        "region": "Bourgogne",
        "color": "Blanc",
        "grape": "Chardonnay",
        "quantity": 1,
        "status": "En cave",
        "price": 280,
        "estimated_value": 340,
        "purchase_place": "Caviste Paris",
        "purchase_date": "2019-05-22",
        "description": "Grand blanc de Bourgogne bio.",
        "tasting_note": "Arômes beurrés, minéralité.",
        "rating": 5,
    },
    {
        "name": "Whispering Angel Rosé",
        "year": 2022,
        "productor": "Château d'Esclans",
        "country": "France",
        "region": "Provence", 
        "color": "Rosé",
        "grape": "Grenache, Cinsault, Rolle",
        "quantity": 4,
        "status": "En cave",
        "price": 18,
        "estimated_value": 22,
        "purchase_place": "Intermarché",
        "purchase_date": "2023-06-01",
        "description": "Rosé tendance, parfait pour l'été.",
        "tasting_note": "Frais, notes de fruits rouges.",
        "rating": 4,
    },
    {
        "name": "Champagne Bollinger Special Cuvée",
        "year": 2014,
        "productor": "Bollinger",
        "country": "France",
        "region": "Champagne",
        "color": "Pétillant",
        "grape": "Pinot Noir, Chardonnay, Pinot Meunier",
        "quantity": 1,
        "status": "En cave",
        "price": 45,
        "estimated_value": 60,
        "purchase_place": "Cave à Champagne",
        "purchase_date": "2020-12-20",
        "description": "Champagne mythique, parfait pour les fêtes.",
        "tasting_note": "Bulles fines, arômes briochés.",
        "rating": 5,
    },
    {
        "name": "Sassicaia",
        "year": 2016,
        "productor": "Tenuta San Guido",
        "country": "Italie",
        "region": "Toscane",
        "color": "Rouge",
        "grape": "Cabernet Sauvignon, Cabernet Franc",
        "quantity": 1,
        "status": "En cave",
        "price": 210,
        "estimated_value": 320,
        "purchase_place": "Enoteca Italienne",
        "purchase_date": "2021-03-18",
        "description": "Super Toscan légendaire.",
        "tasting_note": "Fruits noirs, tanins puissants, boisé élégant.",
        "rating": 5,
    },
    {
        "name": "Pingus",
        "year": 2012,
        "productor": "Dominio de Pingus",
        "country": "Espagne",
        "region": "Ribera del Duero",
        "color": "Rouge",
        "grape": "Tempranillo",
        "quantity": 1,
        "status": "En cave",
        "price": 800,
        "estimated_value": 1200,
        "purchase_place": "Enchères",
        "purchase_date": "2017-05-04",
        "description": "Icône espagnole, rareté.",
        "tasting_note": "Puissant, intense, longueur impressionnante.",
        "rating": 5,
    },
    {
        "name": "Cloudy Bay Sauvignon Blanc",
        "year": 2021,
        "productor": "Cloudy Bay",
        "country": "Nouvelle-Zélande",
        "region": "Marlborough",
        "color": "Blanc",
        "grape": "Sauvignon Blanc",
        "quantity": 2,
        "status": "En cave",
        "price": 29,
        "estimated_value": 35,
        "purchase_place": "Vinatis",
        "purchase_date": "2022-09-15",
        "description": "Sauvignon iconique du Nouveau Monde.",
        "tasting_note": "Notes exotiques, agrumes, vivacité.",
        "rating": 4,
    },
    {
        "name": "Taylor's Vintage Port",
        "year": 2000,
        "productor": "Taylor Fladgate",
        "country": "Portugal",
        "region": "Douro",
        "color": "Autre",
        "grape": "Touriga Nacional, Touriga Francesa",
        "quantity": 1,
        "status": "En cave",
        "price": 95,
        "estimated_value": 180,
        "purchase_place": "Vins Portugais",
        "purchase_date": "2015-12-12",
        "description": "Grand Porto millésimé.",
        "tasting_note": "Riche, puissant, finale sucrée.",
        "rating": 5,
    },
    {
        "name": "Penfolds Grange",
        "year": 2010,
        "productor": "Penfolds",
        "country": "Australie",
        "region": "Australie Méridionale",
        "color": "Rouge",
        "grape": "Shiraz",
        "quantity": 1,
        "status": "Bue",
        "price": 400,
        "estimated_value": 600,
        "purchase_place": "Import Australie",
        "purchase_date": "2018-11-01",
        "description": "Icône australien, bu lors d'un anniversaire.",
        "tasting_note": "Epicé, fruits noirs, puissance.",
        "rating": 5,
    },
    {
        "name": "Trimbach Riesling",
        "year": 2019,
        "productor": "Maison Trimbach",
        "country": "France",
        "region": "Alsace",
        "color": "Blanc",
        "grape": "Riesling",
        "quantity": 3,
        "status": "En cave",
        "price": 16,
        "estimated_value": 20,
        "purchase_place": "Cave Alsace",
        "purchase_date": "2021-08-10",
        "description": "Riesling sec, belle fraîcheur.",
        "tasting_note": "Agrumes, minéralité, longueur.",
        "rating": 4,
    },
]

# Récupérer le superuser admin
admin_user = User.objects.get(username='admin')

for item in data:
    Bottle.objects.create(owner=admin_user, **item)

print(f"✅ {len(data)} bouteilles ajoutées pour l'utilisateur admin !")